export const EXTENSION = /\.ts$|\.js$/;

export const DISCLAIMER = `// Do not edit this file!
// The content are generated automatically`;

export const IMPORTS = [
  `import '@busy-hour/blaze';`,
  `import type {
  ActionsExtractor,
  EventsExtractor,
} from '@busy-hour/blaze-types/dist/types/types/internal';`,
];
